# Generated by Django 5.0.6 on 2024-05-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='month_year',
            field=models.CharField(max_length=255),
        ),
    ]
