# Generated by Django 5.0.6 on 2024-05-25 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_dsc_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='designation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examiner',
            name='institute',
            field=models.TextField(default='IIIT Bhubaneswar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examiner',
            name='is_indian',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='foreign_examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreign', to='users.examiner'),
        ),
        migrations.AddField(
            model_name='user',
            name='indian_examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indian', to='users.examiner'),
        ),
    ]
