# Generated by Django 5.0.6 on 2024-05-19 18:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_comment_remove_form6_comments_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='examiner',
            name='is_indian',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examiner',
            name='priority',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
