# Generated by Django 5.0.6 on 2024-05-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_dsccommittee_examiner_profile_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsccommittee',
            name='email',
            field=models.EmailField(default='naman1@mail.com', max_length=254),
            preserve_default=False,
        ),
    ]
