# Generated by Django 5.0.6 on 2024-05-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_form3c_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form5',
            name='affliation',
        ),
        migrations.RemoveField(
            model_name='form5',
            name='date',
        ),
        migrations.RemoveField(
            model_name='form5',
            name='name_of_examiner',
        ),
        migrations.RemoveField(
            model_name='form5',
            name='place',
        ),
        migrations.RemoveField(
            model_name='form5',
            name='professor',
        ),
    ]
