# Generated by Django 5.0.6 on 2024-05-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_form5_affliation_remove_form5_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form6',
            name='committee',
        ),
    ]
