# Generated by Django 5.0.6 on 2024-05-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_form6_committee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
