# Generated by Django 5.0.6 on 2024-05-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comments_by_foreign',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='comments_by_indian',
            field=models.TextField(blank=True, null=True),
        ),
    ]
