# Generated by Django 5.0.6 on 2024-05-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_comments_by_foreign_user_comments_by_indian'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='softcopy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form1a',
            name='softcopy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form1b',
            name='softcopy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form2',
            name='softcopy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form3a',
            name='softcopy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form3b',
            name='softcopy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form3c',
            name='softcopy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form4a',
            name='softcopy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form4b',
            name='softcopy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form4c',
            name='softcopy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form4d',
            name='softcopy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form4e',
            name='softcopy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form5',
            name='softcopy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='form6',
            name='softcopy_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
