# Generated by Django 5.0.6 on 2024-05-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_examiner_softcopy_url_form1a_softcopy_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examiner',
            name='softcopy_url',
        ),
    ]
